{
"module"  : "Gene Ontology",
"comment" : "Description avalaible on http://geneontology.org/page/download-ontology",
"version" : "1.0",
"owl"     : "",
"rdf"     : [
"@prefix : <http://www.semanticweb.org/irisa/ontologies/2016/1/igepp-ontology#> .",
"@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
"@prefix prov: <http://www.w3.org/ns/prov#> .",
"@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
"@prefix rdfg: <http://www.w3.org/2004/03/trix/rdfg-1/> .",
"@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
"@prefix owl: <http://www.w3.org/2002/07/owl#> .",
"@prefix displaySetting: <http://www.irisa.fr/dyliss/rdfVisualization/display> .",
"@prefix dc: <http://purl.org/dc/elements/1.1/> .",
"",
"@prefix obo: <http://purl.obolibrary.org/obo/> .",
"@prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#> .",
"@prefix go:<http://purl.org/obo/owl/GO#> .",
"",
"@base <http://www.semanticweb.org/irisa/ontologies/2016/1/igepp-ontology#> .",
"<http://www.semanticweb.org/irisa/ontologies/2016/1/igepp-ontology#> rdf:type owl:Ontology .",
"",
"owl:Class displaySetting:entity \"true\"^^xsd:boolean.",
"",
"oboInOwl:id displaySetting:attribute \"true\"^^xsd:boolean .",
"oboInOwl:id rdf:type owl:DatatypeProperty ;",
"   rdfs:label \"ID\" ;",
"   rdfs:domain owl:Class ;",
"   rdfs:range xsd:string .",
"",
"obo:IAO_0000115 displaySetting:attribute \"true\"^^xsd:boolean .",
"obo:IAO_0000115 rdf:type owl:DatatypeProperty ;",
"   rdfs:label \"IAODefinition\" ;",
"   rdfs:domain owl:Class ;",
"   rdfs:range xsd:string .",
"",
"rdfs:comment displaySetting:attribute \"true\"^^xsd:boolean .",
"rdfs:comment rdf:type owl:DatatypeProperty ;",
"   rdfs:label \"Comment\" ;",
"   rdfs:domain owl:Class ;",
"   rdfs:range xsd:string .",
"",
"oboInOwl:hasDefinition displaySetting:attribute \"true\"^^xsd:boolean .",
"oboInOwl:hasDefinition rdf:type owl:DatatypeProperty ;",
"   rdfs:label \"Definition\" ;",
"   rdfs:domain owl:Class ;",
"   rdfs:range xsd:string .",
"",
"oboInOwl:hasOBONamespace displaySetting:attribute \"true\"^^xsd:boolean .",
"oboInOwl:hasOBONamespace rdf:type owl:DatatypeProperty ;",
"   rdfs:label \"OBONamespace\" ;",
"   rdfs:domain owl:Class ;",
"   rdfs:range xsd:string .",
"",
"oboInOwl:hasBroadSynonym displaySetting:attribute \"true\"^^xsd:boolean .",
"oboInOwl:hasBroadSynonym rdf:type owl:DatatypeProperty ;",
"   rdfs:label \"BroadSynonym\" ;",
"   rdfs:domain owl:Class ;",
"   rdfs:range xsd:string .",
"",
"oboInOwl:hasRelatedSynonym displaySetting:attribute \"true\"^^xsd:boolean .",
"oboInOwl:hasRelatedSynonym rdf:type owl:DatatypeProperty ;",
"   rdfs:label \"RelatedSynonym\" ;",
"   rdfs:domain owl:Class ;",
"   rdfs:range xsd:string .",
"",
"oboInOwl:hasExactSynonym displaySetting:attribute \"true\"^^xsd:boolean .",
"oboInOwl:hasExactSynonym rdf:type owl:DatatypeProperty ;",
"   rdfs:label \"ExactSynonym\" ;",
"   rdfs:domain owl:Class ;",
"   rdfs:range xsd:string .",
"",
"oboInOwl:hasNarrowSynonym displaySetting:attribute \"true\"^^xsd:boolean .",
"oboInOwl:hasNarrowSynonym rdf:type owl:DatatypeProperty ;",
"   rdfs:label \"NarrowSynonym\" ;",
"   rdfs:domain owl:Class ;",
"   rdfs:range xsd:string .",
"",
"oboInOwl:hasDbXref displaySetting:attribute \"true\"^^xsd:boolean .",
"oboInOwl:hasDbXref rdf:type owl:DatatypeProperty ;",
"   rdfs:label \"DbXref\" ;",
"   rdfs:domain owl:Class ;",
"   rdfs:range xsd:string ."
]
}
