{
    "comment": "provides a set of classes, properties, and restrictions that can be used to represent and interchange provenance information generated in different systems and under different contexts.",
    "module": "The PROV Ontology",
    "owl": "https://dvcs.w3.org/hg/prov/raw-file/600c6fd1fdb4/ontology/ProvenanceOntology.owl",
    "rdf": [
        "@prefix displaySetting: <http://www.irisa.fr/dyliss/rdfVisualization/display>.",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.",
        "<http://www.w3.org/ns/prov#Usage> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Agent> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Agent> displaySetting:startPoint \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#ActivityInfluence> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#ActivityInfluence> displaySetting:startPoint \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#AgentInfluence> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#AgentInfluence> displaySetting:startPoint \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Derivation> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Derivation> displaySetting:startPoint \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Influence> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Influence> displaySetting:startPoint \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Activity> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Activity> displaySetting:startPoint \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#endedAtTime> displaySetting:attribute \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#startedAtTime> displaySetting:attribute \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#EntityInfluence> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#EntityInfluence> displaySetting:startPoint \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Invalidation> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Collection> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Collection> displaySetting:startPoint \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Start> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#PrimarySource> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/2002/07/owl#Thing> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/2002/07/owl#Thing> rdfs:label \"http://www.w3.org/2002/07/owl#Thing\"^^xsd:string.",
        "<http://www.w3.org/ns/prov#Role> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Plan> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Attribution> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#End> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Entity> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Entity> displaySetting:startPoint \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#generatedAtTime> displaySetting:attribute \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#invalidatedAtTime> displaySetting:attribute \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Association> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Association> displaySetting:startPoint \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Generation> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Revision> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Quotation> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Communication> displaySetting:entity \"true\"^^xsd:boolean.",
        "<http://www.w3.org/ns/prov#Delegation> displaySetting:entity \"true\"^^xsd:boolean."
    ],
    "version": "1.0"
}