SELECT DISTINCT ?subject ?relation ?object
FROM  $graph
WHERE {
  ?subject rdf:type owl:Class .
  ?object rdf:type owl:Class .
  ?relation rdf:type $OwlProperty;
            rdfs:domain ?subject;
            rdfs:range ?object.
}
