SELECT DISTINCT ?entity ?property ?value
WHERE {
    GRAPH $graph {
    ?g rdfg:subGraphOf $graph }
    GRAPH ?g {
	    ?entity ?property ?value.
      ?entity rdf:type owl:Class.
      VALUES ?entity { $entities }
    }
}
