SELECT DISTINCT ?subject ?relation ?object
WHERE {
    GRAPH <urn:sparql:tests-askomics:insert:informative1> {
    ?g rdfg:subGraphOf <urn:sparql:tests-askomics:insert:informative1> .
    }
    GRAPH ?g {
    ?relation rdf:type $OwlProperty;
                rdfs:domain ?subject;
                rdfs:range ?object.
    }
}
