SELECT DISTINCT ?entity ?attribute ?labelAttribute ?typeAttribute
WHERE {
    GRAPH $graph {
    ?g rdfg:subGraphOf $graph }
    GRAPH ?g {
        ?entity rdf:type owl:Class .
	      ?attribute displaySetting:attribute "true"^^xsd:boolean .

        ?attribute rdf:type owl:DatatypeProperty;
					         rdfs:label ?labelAttribute ;
                   rdfs:domain ?entity;
                   rdfs:range ?typeAttribute.

	    VALUES ?entity { $entities }
		VALUES ?typeAttribute { xsd:decimal xsd:string }
    }
}
