SELECT DISTINCT ?entity ?property ?value
WHERE {
    GRAPH <urn:sparql:tests-askomics:insert:informative1> {
    ?g rdfg:subGraphOf <urn:sparql:tests-askomics:insert:informative1> }
    GRAPH ?g {
	    ?entity ?property ?value.
        VALUES ?entity { $entities }
    }
}
