SELECT DISTINCT ?subject ?relation ?object
WHERE {
    GRAPH $graph {
    ?g rdfg:subGraphOf $graph .
    }
  ####  GRAPH ?g {
      ?relation rdf:type $OwlProperty;
                rdfs:domain ?subject;
                rdfs:range ?object.
      ?subject rdf:type owl:Class.
      ?object rdf:type owl:Class.
  ####  }
}
