SELECT DISTINCT ?entity ?category ?labelCategory ?typeCategory
WHERE {
    GRAPH $graph {
    ?g rdfg:subGraphOf $graph }
    GRAPH ?g {
        ?entity rdf:type owl:Class .
	        ?typeCategory displaySetting:category [] .

        ?category rdf:type owl:ObjectProperty;
                    rdfs:label ?labelCategory ;
                    rdfs:domain ?entity;
                    rdfs:range ?typeCategory.

	    VALUES ?entity { $entities }
    }
}
