SELECT DISTINCT $select
WHERE{
    {
        GRAPH $graph {
            ?g rdfg:subGraphOf $graph
        }
    }UNION{
        GRAPH $graph2 {
            ?g rdfg:subGraphOf $graph2
        }
    }

    GRAPH ?g {
        $query
    }
}