SELECT DISTINCT ?relation_label
WHERE{
    {
        GRAPH $graph {
            ?g rdfg:subGraphOf $graph
        }
    }UNION{
        GRAPH $graph2 {
            ?g rdfg:subGraphOf $graph2
        }
    }

    GRAPH ?g {
        ?class rdf:type owl:Class .
        OPTIONAL { ?relation rdfs:domain ?class } .
        OPTIONAL { ?relation rdfs:range ?range } .
        OPTIONAL { ?relation rdfs:label ?relation_label } .
        VALUES ?class { :$nodeClass }
    }
}