SELECT DISTINCT ?nodeUri ?nodeLabel
WHERE {
    GRAPH $graph {
    ?g rdfg:subGraphOf $graph }
    GRAPH ?g {
        ?nodeUri displaySetting:startPoint "true"^^xsd:boolean .
        ?nodeUri rdfs:label ?nodeLabel
    }
}
