SELECT DISTINCT $select
WHERE{
    {
        GRAPH $public_graph {
            ?g rdfg:subGraphOf $public_graph
        }
    }UNION{
        GRAPH $private_graph {
            ?g rdfg:subGraphOf $private_graph
        }
    }

    GRAPH ?g {
        $query
    }
}